
    create table carts (
       id int8 generated by default as identity,
        created_at timestamp not null,
        lastModified timestamp not null,
        status varchar(255) not null,
        customer_id int8,
        primary key (id)
    );

    create table categories (
       id int8 generated by default as identity,
        created_at timestamp not null,
        lastModified timestamp not null,
        description varchar(255) not null,
        name varchar(255) not null,
        primary key (id)
    );

    create table customers (
       id int8 generated by default as identity,
        created_at timestamp not null,
        lastModified timestamp not null,
        email varchar(255),
        enabled boolean not null,
        first_name varchar(255),
        last_name varchar(255),
        telephone varchar(255),
        primary key (id)
    );

    create table order_items (
       id int8 generated by default as identity,
        created_at timestamp not null,
        lastModified timestamp not null,
        quantity int8 not null,
        order_id int8,
        product_id int8,
        primary key (id)
    );

    create table orders (
       id int8 generated by default as identity,
        created_at timestamp not null,
        lastModified timestamp not null,
        total_price numeric(10, 2) not null,
        address_1 varchar(255),
        address_2 varchar(255),
        city varchar(255),
        country varchar(2) not null,
        postcode varchar(10) not null,
        shipped timestamp,
        status varchar(255) not null,
        cart_id int8,
        payment_id int8,
        primary key (id)
    );

    create table payments (
       id int8 generated by default as identity,
        created_at timestamp not null,
        lastModified timestamp not null,
        amount numeric(19, 2) not null,
        paypal_payment_id varchar(255),
        status varchar(255) not null,
        primary key (id)
    );

    create table products (
       id int8 generated by default as identity,
        created_at timestamp not null,
        lastModified timestamp not null,
        description varchar(255) not null,
        name varchar(255) not null,
        price numeric(10, 2) not null,
        sales_counter int4,
        status varchar(255) not null,
        category_id int8,
        primary key (id)
    );

    create table products_reviews (
       product_id int8 not null,
        reviews_id int8 not null,
        primary key (product_id, reviews_id)
    );

    create table reviews (
       id int8 generated by default as identity,
        created_at timestamp not null,
        lastModified timestamp not null,
        description varchar(255) not null,
        rating int8 not null,
        title varchar(255) not null,
        primary key (id)
    );

    alter table if exists orders 
       add constraint UK_haujdjk1ohmeixjhnhslchrp1 unique (payment_id);

    alter table if exists products_reviews 
       add constraint UK_rba1wlsrla9h6pt9v7lrtc1mr unique (reviews_id);

    alter table if exists carts 
       add constraint FK8ba3sryid5k8a9kidpkvqipyt 
       foreign key (customer_id) 
       references customers;

    alter table if exists order_items 
       add constraint FKbioxgbv59vetrxe0ejfubep1w 
       foreign key (order_id) 
       references orders;

    alter table if exists order_items 
       add constraint FKocimc7dtr037rh4ls4l95nlfi 
       foreign key (product_id) 
       references products;

    alter table if exists orders 
       add constraint FK594fgx8wpklcf3t41jq3grhlh 
       foreign key (cart_id) 
       references carts;

    alter table if exists orders 
       add constraint FK8aol9f99s97mtyhij0tvfj41f 
       foreign key (payment_id) 
       references payments;

    alter table if exists products 
       add constraint FKog2rp4qthbtt2lfyhfo32lsw9 
       foreign key (category_id) 
       references categories;

    alter table if exists products_reviews 
       add constraint FKi9i0n1o7cjlnker2o2hgl0ueq 
       foreign key (reviews_id) 
       references reviews;

    alter table if exists products_reviews 
       add constraint FKp0p3bq7p29sc9hhvix54g5l2g 
       foreign key (product_id) 
       references products;
